module.exports = [ 
    { 
        transactionId: "Direct Deposit JN2021-01-RR",
        amount: 780,
        from: "Uber Technologies Inc.",
        flag: "Income",
        date: "2021-05-01",
        notes: "First payment of the month",
        idx: 0,
     },
     { 
        transactionId: "BED BATH & BEYOND #65 973-785",
        amount: -150,
        from: "Bed Bath & Beyond",
        flag: "Purchase",
        date: "2021-05-01",
        notes: "Ninja blender for Mom!",
        idx: 1,
     },
     { 
        date: "2021-05-05",
        transactionId: "CON ED OF NY INTELL CK PPD ID: 2462467002",
        amount: -91.52,
        from: "Con Eddison of New York",
        flag: "Utility",
        notes: "Electricity bill of May",
        idx: 2,
     },
     { 
        date: "2021-05-08",
        transactionId: "NATIONAL GRID NY UTILITYPAY PPD",
        amount: -28.02,
        from: "National Grid New York",
        flag: "Utility",
        notes: "Gas bill of May",
        idx: 3,
     },
     { 
        date: "2021-05-11",
        transactionId: "Direct Deposit JN2021-11-WQ",
        amount: 510,
        from: "Uber Technologies Inc.",
        flag: "Income",
        notes: "Second payment of the month",
        idx: 4,
     },
 ]